server:
  port: 8070
spring:
  application:
    name: activities
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/Tourisme
    username: postgres
    password: "0000"
  jpa:
    hibernate:
      ddl-auto: create
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

application:
  config:
    auth-url: http://localhost:8222/api/v1/auth

management:
  tracing:
    sampling:
      probability: 1.0