eureka:
  client:
    register-with-eureka: false
server:
  port: 8222
spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: auth
          uri: http://localhost:8090
          predicates:
            - Path=/api/v1/auth/** , /api/v1/users/**
        - id: activities
          uri: http://localhost:8070
          predicates:
            - Path=/api/v1/activities/**

management:
  tracing:
    sampling:
      probability: 1.0